Algoritmo "maiorque10"
//Elabore um algoritmo para ler um valor e escrever a mensagem: É MAIOR QUE 10!
//se o valor lido for maior que 10, caso contrário escrever NÃO É MAIOR QUE 10!
Var
   valor: real

Inicio

   escreva("Digite um número: ")
   leia(valor)

   escreval()

   se (valor > 10.0) entao
      escreva("É MAIOR QUE 10!")

   senao
      escreva("NÃO É MAIOR QUE 10!")

   fimse

Fimalgoritmo